version: "3.9"

services:

  php:
    build:
      context: ./../
      dockerfile: container/Dockerfile
      target: development
    container_name: ${PROJECT_NAME}_php
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
        reservations:
          cpus: "1.0"
          memory: "1024M"
    read_only: true
    tmpfs:
      - /tmp:uid=1000,gid=1000
      - /.composer:uid=1000,gid=1000
      - /var/log:uid=1000,gid=1000
      - /var/log/nginx:uid=1000,gid=1000
      - /var/run:uid=1000,gid=1000
    user: 1000:1000
    volumes:
      - ./../symfony:/var/www/application
      - ./../symfony/var:/var/www/application/var:uid=1000,gid=1000
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      application:
        aliases:
          - api.local

networks:
  application:
    driver: bridge
