overblog_graphql:
  definitions:
    schema:
      query: Query
    mappings:
      auto_discover: true
      types:
        - type: yaml
          dir: "%kernel.project_dir%/config/graphql/types"
          suffix: null
