Query:
  type: object
  config:
    description: "The GraphQL Query Interface"
    fields:
      example:
        type: Example
        resolve: '@=query("App\\ExampleResolver::resolve")'
      greeting:
        type: Greeting
        resolve: '@=query("App\\GreetingResolver::resolve")'
        args:
          name:
            type: String
